# Generated by Django 4.0.5 on 2022-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='Hello buddy Welcome.Thanks for visiting my bio.Please mail me if necessary.', max_length=256),
        ),
    ]
