# Generated by Django 4.0.5 on 2022-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userprofile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='Hello buddy Welcome . Thanks for visiting my profile . Please send mail to conact me.', max_length=256),
        ),
    ]
