# Generated by Django 4.0.5 on 2022-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('general', 'genral'), ('food', 'food'), ('travel', 'travel'), ('healt', 'healt'), ('education', 'education'), ('entertainment', 'entertainment'), ('it', 'it'), ('politics', 'politics'), ('geo_politics', 'geo_politics'), ('commerce', 'commerce'), ('culture', 'culture'), ('sports', 'sports'), ('environment', 'environment'), ('religion', 'religion')], default='genl', max_length=20),
        ),
    ]
