# Generated by Django 4.0.5 on 2022-06-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_date',
            new_name='comment_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('general', 'genral'), ('food', 'food'), ('travel', 'travel'), ('health', 'health'), ('education', 'education'), ('entertainment', 'entertainment'), ('it', 'it'), ('politics', 'politics'), ('geo_politics', 'geo_politics'), ('commerce', 'commerce'), ('culture', 'culture'), ('sports', 'sports'), ('environment', 'environment'), ('religion', 'religion')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_loved', to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
